const gameThemes = [
  'Personagens da ficção com quem você gostaria de ter um encontro',
  'Pessoas famosas que você gostaria de ser',
  'Lugares onde você gostaria de morar',
  'Poderes especiais que você gostaria de ter',
  'Coisas que te dão medo',
  'Itens do dia a dia que poderiam ser boas armas',
  'Mentiras que você acreditaria',
  'Sabores de sorvete que poderiam ser deliciosos',
  'Itens/armas que você gostaria de ter para lutar contra zumbis',
  'Personagens da ficção que você gostaria de ser',
  'Coisas que você desejava quando criança',
  'Presentes de aniversário que você gostaria de ganhar',
  'Países populares para viajar',
  'Coisas fofinhas',
  'Pense como um gato: os lugares mais confortáveis do mundo',
  'Pedidos de casamento que te fariam feliz',
  'Itens úteis quando você está perdido(a) no deserto',
  'Itens encontrados em um baú do tesouro que você gostaria de ter',
  'Momentos históricos que você visitaria se tivesse uma máquina do tempo',
  'Pense como um cientista: o que você gostaria de descobrir?',
  'Itens úteis para levar a uma ilha deserta',
  'Piadas mais engraçadas',
  'Títulos de livros que te deixariam curioso para saber seu conteúdo',
  'Pense como um mago: qual seria o seu feitiço favorito?',
  'As coisas mais bonitas do mundo',
  'Pense como um explorador: que lugares te deixam animado?',
  'Mundos imaginários que você gostaria de visitar',
  'Coisas que você ficaria feliz em encontrar no seu bolso ou bolsa',
  'Um único prato pra comer até o fim da vida',
  'Lugares que você gostaria de explorar no espaço',
  'Superpoderes mais engraçados',
  'Coisas que te deixam animado ao final de semana',
  'Animais que você gostaria de ter como melhor amigo',
  'Instrumentos musicais que você gostaria de aprender',
  'Habilidades que você gostaria de aprender instantaneamente',
  'As melhores invenções de todos os tempos',
  'Cidades que você adoraria visitar em um futuro próximo',
  'Ideias de negócios engraçadas que poderiam dar certo',
  'Coisas que você levaria para um apocalipse alienígena',
  'Coisas que você faria se pudesse viajar no tempo',
  'Melhores maneiras de escapar de um castelo assombrado',
  'Lugares inusitados onde você gostaria de morar',
  'Comidas que você sempre pede no delivery',
  'Filmes ou séries que você assistiria de novo',
  'Coisas que você guardaria em um cofre',
];
