const gameThemes = [
  'Esportes mais conhecidos',
  'Contos de fadas populares',
  'Personagens da ficção com quem você gostaria de ter um encontro',
  'Pessoas famosas que você gostaria de ser',
  'Lugares onde você gostaria de morar',
  'Poderes especiais que você gostaria de ter',
  'Filmes conhecidos',
  'Coisas que te dão medo',
  'Itens do dia a dia que poderiam ser boas armas',
  'Coisas que você não conseguiria perdoar',
  'Coisas nas quais você gostaria de ficar em imersão',
  'Coisas que você gostaria de fotografar',
  'Coisas que você ficaria olhando com admiração o dia inteiro',
  'Mentiras que você acreditaria',
  'Sabores de sorvete que poderiam ser deliciosos',
  'Coisas importantes na vida',
  'Habilidades importantes para ser líder',
  'Coisas que te fazem feliz',
  'Itens / armas que você gostaria de ter para lutar contra zumbis',
  'Atletas famosos',
  'Comidas famosas',
  'Personagens da ficção que você gostaria de ser',
  'Celebridades de filmes e séries mais conhecidas da atualidade',
  'Coisas que cheiram bem',
  'Coisas que você gostaria de ter como souvenir',
  'Coisas que você gostaria de fazer quando se aposentar',
  'Coisas difíceis de suportar',
  'Coisas importantes para fazer sucesso nas mídias sociais',
  'Habilidades essenciais para um comediante',
  'Canções famosas',
  'Figuras históricas populares',
  'Marcas mais valiosas',
  'Coisas que você desejava quando criança',
  'Coisas que você quer fazer logo quando acorda',
  'Coisas úteis em uma casa',
  'Sons que te fazem feliz',
  'Coisas que fazem você se sentir amado(a)',
  'Presentes de aniversário mais comuns',
  'Vilões mais temíveis',
  'Países populares para viajar',
  'Coisas fofinhas',
  'Atividades difíceis de serem feitas sozinho(a)',
  'Animais nos quais você gostaria de montar',
  'Habilidades úteis para o trabalho',
  'Pense como uma criança: o que te faz feliz?',
  'Pense como um gato: os lugares mais confortáveis do mundo',
  'Brinquedos mais conhecidos',
  'Palavras que você gostaria de ouvir',
  'Drinques populares',
  'Coisas que te deixam com sono',
  'Veículos mais comuns',
  'Pedidos de casamento que te fariam feliz',
  'Itens úteis quando você está perdido(a) no deserto',
  'Itens encontrados em um baú do tesouro que você gostaria de ter',
  'Momentos históricos que você visitaria se tivesse uma máquina do tempo',
  'Alimentos que fazem bem',
  'Coisas confiáveis por todo o sempre',
  'Tipos de festivais que você gostaria de participar',
  'Pense como um vilão: qual seria o personagem heróico que você menos gostaria de enfrentar?',
  'Pense como um cientista: o que você gostaria de descobrir?',
  'Itens úteis para levar a uma ilha deserta',
  'Melhores jogos de tabuleiro já lançados',
  'Piadas mais engraçadas',
  'Itens diferentões que você gostaria de ter',
  'Melhores nomes de golpes especiais para gritar',
  'Características de pessoas que você gostaria de ter em seu círculo de amizade',
  'Títulos de livros que te deixariam curioso para saber seu conteúdo',
  'Pense como um mago: qual seria o seu feitiço favorito?',
  'Pense como um cachorro: o que te faz feliz?',
  'Coisas que surpreenderiam se fossem ditas por um professor',
  'As coisas mais bonitas do mundo',
  'Coisas populares com crianças',
  'Os doces mais conhecidos',
  'Os nomes mais legais',
  'Amor verdadeiro ou apenas uma aventura?',
  'Coisas que você faz quando está de bom humor',
  'Pense como um herói: qual seria sua pose?',
  'Pense como um explorador: que lugares te deixam animado?',
  'Mundos imaginários que você gostaria de visitar',
  'Habilidades úteis em relacionamentos',
  'Personagens mais fortes da ficção',
  'Coisas que você ficaria feliz em encontrar no seu bolso ou bolsa',
  'Lugares onde mais acontecem encontros românticos',
  'Um único prato pra comer até o fim da vida',
  'Ações e atitudes que exigem coragem',
  'Pense como um adolescente: o que seria algo ruim se acontecesse durante a aula?',
  'Personagens fictícios com os piores temperamentos',
  'Habilidades importantes para um streamer',
  'Lugares que você gostaria de explorar no espaço',
  'Superpoderes mais engraçados',
  'Coisas que te deixam animado ao final de semana',
  'Animais que você gostaria de ter como melhor amigo',
  'Títulos de filmes que fariam você rir só de ouvir',
  'Programas de TV que você assistia quando criança',
  'Itens de videogame que você gostaria de ter na vida real',
  'Festas temáticas em que você adoraria participar',
  'Instrumentos musicais que você gostaria de aprender',
  'Lugares mais relaxantes do mundo',
  'Veículos mais estilosos para dirigir',
  'Coisas que te fazem sentir nostálgico',
  'Habilidades que você gostaria de aprender instantaneamente',
  'As melhores invenções de todos os tempos',
  'Cidades que você adoraria visitar em um futuro próximo',
  'Ideias de negócios engraçadas que poderiam dar certo',
  'Desafios estranhos que seriam divertidos de fazer em grupo',
  'Hobbies que você gostaria de experimentar',
  'Os esportes mais emocionantes que você gostaria de praticar',
  'Filmes de ficção científica que te fazem pensar',
];
